// <auto-generated />
using System;
using Cookle.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cookle.Migrations
{
    [DbContext(typeof(CookleContext))]
    [Migration("20190504143655_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cookle.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Cookle.Models.Frigorifico", b =>
                {
                    b.Property<int>("User");

                    b.Property<int>("Ingrediente");

                    b.Property<DateTime>("Data");

                    b.Property<int>("Quantidade")
                        .HasMaxLength(2147483647);

                    b.HasKey("User", "Ingrediente");

                    b.HasAlternateKey("Ingrediente", "User");

                    b.ToTable("Frigorifico");
                });

            modelBuilder.Entity("Cookle.Models.Historico", b =>
                {
                    b.Property<int>("User");

                    b.Property<int>("Receita");

                    b.Property<int>("Numero");

                    b.Property<DateTime>("UltimaVez");

                    b.HasKey("User", "Receita");

                    b.HasAlternateKey("Receita", "User");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("Cookle.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("Cookle.Models.IngredienteReceita", b =>
                {
                    b.Property<int>("Ingrediente");

                    b.Property<int>("Receita");

                    b.Property<float>("Quantidade")
                        .HasMaxLength(2147483647);

                    b.Property<int>("Unidade")
                        .HasMaxLength(2147483647);

                    b.HasKey("Ingrediente", "Receita");

                    b.HasIndex("Receita");

                    b.ToTable("IngredienteReceita");
                });

            modelBuilder.Entity("Cookle.Models.Morada", b =>
                {
                    b.Property<string>("Rua");

                    b.Property<string>("Cidade");

                    b.Property<int>("Pais");

                    b.Property<string>("CodigoPostal");

                    b.HasKey("Rua", "Cidade", "Pais", "CodigoPostal");

                    b.HasAlternateKey("Cidade", "CodigoPostal", "Pais", "Rua");

                    b.HasIndex("Pais");

                    b.ToTable("Morada");
                });

            modelBuilder.Entity("Cookle.Models.Nota", b =>
                {
                    b.Property<int>("User");

                    b.Property<int>("Receita");

                    b.Property<int>("Id");

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("User", "Receita", "Id");

                    b.HasAlternateKey("Id", "Receita", "User");

                    b.HasIndex("Receita");

                    b.ToTable("Nota");
                });

            modelBuilder.Entity("Cookle.Models.Nutriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("Unidade")
                        .HasMaxLength(2147483647);

                    b.HasKey("Id");

                    b.ToTable("Nutriente");
                });

            modelBuilder.Entity("Cookle.Models.NutrienteReceita", b =>
                {
                    b.Property<int>("Nutriente");

                    b.Property<int>("Receita");

                    b.Property<float>("Quantidade")
                        .HasMaxLength(2147483647);

                    b.HasKey("Nutriente", "Receita");

                    b.HasIndex("Receita");

                    b.ToTable("NutrienteReceita");
                });

            modelBuilder.Entity("Cookle.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("Cookle.Models.Passo", b =>
                {
                    b.Property<int>("Ingrediente");

                    b.Property<int>("Numero");

                    b.Property<string>("Descricao")
                        .HasMaxLength(50);

                    b.Property<int?>("SubReceita");

                    b.HasKey("Ingrediente", "Numero");

                    b.ToTable("Passo");
                });

            modelBuilder.Entity("Cookle.Models.Plano", b =>
                {
                    b.Property<int>("User");

                    b.Property<int>("Receita");

                    b.HasKey("User", "Receita");

                    b.HasAlternateKey("Receita", "User");

                    b.ToTable("Plano");
                });

            modelBuilder.Entity("Cookle.Models.PreferenciaIngrediente", b =>
                {
                    b.Property<int>("User");

                    b.Property<int>("Ingrediente");

                    b.Property<int>("Tipo")
                        .HasMaxLength(2147483647);

                    b.HasKey("User", "Ingrediente");

                    b.HasAlternateKey("Ingrediente", "User");

                    b.ToTable("PreferenciaIngrediente");
                });

            modelBuilder.Entity("Cookle.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("Dificuldade")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Imagem")
                        .HasMaxLength(45);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int?>("NumPessoas")
                        .HasMaxLength(2147483647);

                    b.Property<int?>("TempoPrep")
                        .HasMaxLength(2147483647);

                    b.Property<int?>("Tipo")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Video")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("Cookle.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("Sexo");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<bool>("Voz");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Cookle.Models.Frigorifico", b =>
                {
                    b.HasOne("Cookle.Models.Ingrediente", "Ingredientes")
                        .WithMany()
                        .HasForeignKey("Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.Historico", b =>
                {
                    b.HasOne("Cookle.Models.Receita", "Receitas")
                        .WithMany()
                        .HasForeignKey("Receita")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.IngredienteReceita", b =>
                {
                    b.HasOne("Cookle.Models.Ingrediente", "Ingredientes")
                        .WithMany()
                        .HasForeignKey("Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.Receita", "Receitas")
                        .WithMany()
                        .HasForeignKey("Receita")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.Morada", b =>
                {
                    b.HasOne("Cookle.Models.Pais", "Paises")
                        .WithMany()
                        .HasForeignKey("Pais")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.Nota", b =>
                {
                    b.HasOne("Cookle.Models.Receita", "Receitas")
                        .WithMany()
                        .HasForeignKey("Receita")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.NutrienteReceita", b =>
                {
                    b.HasOne("Cookle.Models.Nutriente", "Nutrientes")
                        .WithMany()
                        .HasForeignKey("Nutriente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.Receita", "Receitas")
                        .WithMany()
                        .HasForeignKey("Receita")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.Passo", b =>
                {
                    b.HasOne("Cookle.Models.Ingrediente", "Ingredientes")
                        .WithMany()
                        .HasForeignKey("Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.Plano", b =>
                {
                    b.HasOne("Cookle.Models.Receita", "Receitas")
                        .WithMany()
                        .HasForeignKey("Receita")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cookle.Models.PreferenciaIngrediente", b =>
                {
                    b.HasOne("Cookle.Models.Ingrediente", "Ingredientes")
                        .WithMany()
                        .HasForeignKey("Ingrediente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Cookle.Models.User", "Users")
                        .WithMany()
                        .HasForeignKey("User")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
